version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  backend:
    container_name: backend
    build: backend
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./backend:/code
    ports:
     - "80:80"
    depends_on:
     - db
  ng:
    container_name: ng
    build: frontend
    ports:
      - "8000:80"