# Generated by Django 3.0.5 on 2020-04-04 13:31

import autoslug.fields
import datetime
from django.db import migrations, models
import froala_editor.fields
import trips.models


def get_autoslug_populate_from(instance):
    return instance.name


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Trip')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=get_autoslug_populate_from, verbose_name='Slug')),
                ('date_from', models.DateField(blank=True, default=datetime.date.today, help_text='The date when the trip begins.', null=True, verbose_name='From date')),
                ('date_to', models.DateField(blank=True, default=trips.models.get_default_date_to, help_text='The date when the trip ends.', null=True, verbose_name='To date')),
                ('description', froala_editor.fields.FroalaField(blank=True, verbose_name='Description')),
            ],
        ),
    ]
