# Generated by Django 3.0.5 on 2020-04-24 19:17

from django.db import migrations, models
import django.db.models.deletion
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('trips', '0002_auto_20200405_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=trips.models.photo_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.UserProfile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip')),
            ],
        ),
    ]
